services:
  db:
    image: postgres:17.6
    restart: always
    environment:
      POSTGRES_USER: bento
      POSTGRES_PASSWORD: bento
      POSTGRES_DB: build_angle_development
    ports:
      - '5432:5432'
    volumes:
      - postgres_data_bento:/var/lib/postgresql/data

volumes:
  postgres_data_bento: